spotify:
  target: dev
  outputs:
    dev:
      account: ydb76375.us-east-1
      database: spotify
      password: pyssyz-kudgEg-5gophy
      role: ACCOUNTADMIN
      schema: staging
      threads: 1
      type: snowflake
      user: YANGSTEPHEN613
      warehouse: compute_wh
    prod:
      account: ydb76375.us-east-1
      database: spotify
      password: pyssyz-kudgEg-5gophy
      role: ACCOUNTADMIN
      schema: warehouse
      threads: 1
      type: snowflake
      user: YANGSTEPHEN613
      warehouse: compute_wh

