version: 2

sources:
  - name: spotify
    database: spotify
    schema: raw
    tables: 
      - name: get_songs_by_artist
  - name: spotify
    database: spotify
    schema: raw
    tables: 
      - name: recommendation