version: 2

sources:
  - name: spotify
    database: spotify
    schema: raw
    tables: 
      - name: get_songs_by_artist
  - name: spotify
    database: spotify
    schema: raw
    tables: 
      - name: recommendation
  - name: spotify
    database: spotify
    schema: raw
    tables: 
      - name: new_releases
  - name: spotify
    database: spotify
    schema: raw
    tables: 
      - name: new_releases_album_tracks
  - name: spotify
    database: spotify
    schema: raw
    tables: 
      - name: new_releases_json