spotify:
  outputs:
    dev:
      account: zjb36759.us-east-1
      database: spotify
      password: siWqyg-7jizwa-xosdox
      role: ACCOUNTADMIN
      schema: raw
      threads: 1
      type: snowflake
      user: syang215
      warehouse: compute_wh
  target: dev
