version: 2

sources:
  - name: spotify
    database: spotify
    schema: raw
    tables: 
      - name: new_release
      - name: featured_playlist
      - name: browse_category
  - name: spotify_sg
    database: spotify
    schema: staging
    tables:
      - name: featured_playlist_flatten
      - name: browse_category_flatten
      - name: new_release_flatten
      - name: new_release_track
      - name: featured_playlist_album_artist_track
      - name: browse_category_playist
  - name: spotify_wh
    database: spotify
    schema: warehouse
    tables:
      - name: new_release_album_track
      - name: browse_category_agg


