WITH ALBUM_TRACKS AS (
    SELECT ARTISTS_ID, ARTISTS_NAME, TRACK_ID, TRACK_NAME, ALBUM_ID  FROM {{ source('spotify', 'new_releases_album_tracks') }}
), 
NEW_RELEASES AS (
    SELECT ALBUM_TYPE, ALBUM_ID, ALBUM_NAME, ALBUM_RELEASE_DATE FROM {{ source('spotify', 'new_releases') }}
)
SELECT AT.ARTISTS_ID, AT.ARTISTS_NAME, AT.TRACK_ID, AT.TRACK_NAME, AT.ALBUM_ID, NR.ALBUM_TYPE, NR.ALBUM_NAME, NR.ALBUM_RELEASE_DATE 
FROM ALBUM_TRACKS AT 
JOIN NEW_RELEASES NR ON AT.ALBUM_ID = NR.ALBUM_ID
ORDER BY  ALBUM_RELEASE_DATE, ARTISTS_NAME, ALBUM_NAME
